#端口
server:
  port: 9090
#指定配置
spring:
  profiles:
    active: dev
  devtools:
    restart:
      # 热部署生效
      enabled: true
      # 设置需要重启的目录
      additional-paths: src/java/main
      # 设置不需要重启的目录
      exclude: static/**,public/**,WEB-INF/**
